const MainContents = () => {
    return (
      <>
      <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
                <div>테스트</div>
      </>
    )
}

export default MainContents;