feign:
  client:
    config:
      default:
        loggerLevel: BASIC

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: 'jdbc:mariadb://localhost:3306/tech-recruit'
    username: 'root'
    password: 'root'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true